version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Restaurant
    ports:
      - "5433:5432"
    networks:
      - restaurant-network

  app:
    image: kuroshixd/restaurant-app:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Restaurant
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - restaurant-network

  frontend:
    image: memedealer/my-react-app:latest
    ports:
      - "5173:5173"
    depends_on:
      - app
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge
