name: Build and Run Maven Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven dependencies and build
        run: |
          cd Restaurant-V_Domike_y_Sanycha/Restaurant
          mvn clean install

      - name: Run Spring Boot application
        run: |
          cd Restaurant-V_Domike_y_Sanycha/Restaurant
          mvn spring-boot:run
