name: Build and Run Maven Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug repository structure
        run: ls -R

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Wait for PostgreSQL to be ready
        run: |
          while ! pg_isready -h localhost -p 5432; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Configure database properties
        run: |
          cd /home/runner/work/Restaurant-V_Domike_y_Sanycha/Restaurant-V_Domike_y_Sanycha
          > Restaurant/src/main/resources/application.properties
          echo "spring.application.name=Restaurant" > Restaurant/src/main/resources/application.properties
          echo "spring-jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect" >> Restaurant/src/main/resources/application.properties
          echo "spring.datasource.url=jdbc:postgresql://localhost:5432/postgres" >> Restaurant/src/main/resources/application.properties
          echo "spring.datasource.username=postgres" >> Restaurant/src/main/resources/application.properties
          echo "spring.datasource.password=postgres" >> Restaurant/src/main/resources/application.properties
          echo "spring.jpa.hibernate.ddl-auto=update" >> Restaurant/src/main/resources/application.properties
          echo "spring.jpa.show-sql=true" >> Restaurant/src/main/resources/application.properties

      - name: Install Maven dependencies and build
        run: |
          cd /home/runner/work/Restaurant-V_Domike_y_Sanycha/Restaurant-V_Domike_y_Sanycha/Restaurant
          mvn clean install
      # Don't need to run an application
      #- name: Run Spring Boot application
      #  run: |
      #    cd /home/runner/work/Restaurant-V_Domike_y_Sanycha/Restaurant-V_Domike_y_Sanycha/Restaurant
      #    mvn spring-boot:run
      - name: Run tests
        run: |
          cd /home/runner/work/Restaurant-V_Domike_y_Sanycha/Restaurant-V_Domike_y_Sanycha/Restaurant
          mvn test
